[versions]
kotlin = "2.3.0"
intellijPlatform = "2.10.5"
grammarkit = "2022.3.2.2"
jettison = "1.5.4"
jsonSkema = "0.28.0"

[libraries]
jettison = { group = "org.codehaus.jettison", name = "jettison", version.ref = "jettison" }
jsonSkema = { group = "com.github.erosb", name = "json-sKema", version.ref = "jsonSkema" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit" }
