[versions]
kotlin = "2.3.0"
intellij-platform = "2.10.5"
grammarkit = "2022.3.2.2"
json-jettison = "1.5.4"
json-skema = "0.28.0"
commons-validator = "1.10.1"

[libraries]
json-jettison = { group = "org.codehaus.jettison", name = "jettison", version.ref = "json-jettison" }
json-skema = { group = "com.github.erosb", name = "json-sKema", version.ref = "json-skema" }
commons-validator = { group = "commons-validator", name = "commons-validator", version.ref = "commons-validator" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }
jetbrains-grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit" }
