[versions]
kotlin = "2.3.0"
intellijPlatform = "2.11.0"
grammarkit = "2023.3.0.1"
jettison = "1.5.4"
jsonSkema = "0.28.0"
junit = "4.13.2"

[libraries]
jettison = { module = "org.codehaus.jettison:jettison", version.ref = "jettison" }
jsonSkema = { module = "com.github.erosb:json-sKema", version.ref = "jsonSkema" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit" }
